version: "3.9"

services:
  redis:
    image: redis:latest
    container_name: auth_service_redis
    command: "redis-server --requirepass ${REDIS_AUTH}"
    ports:
      - "6379:6379"
    env_file:
      - .env

  auth-service:
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: auth_service
    command: gunicorn auth_service.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8080
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=auth_service.settings
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_AUTH=${REDIS_AUTH}
    volumes:
      - .:/app
